### ISSUE TITLE
可以选择不下载测试版,64位这些吗，服务器不行，下载太慢还占空间

### ISSUE THREAD

**Issue by wanonymous1** [ChengTu-Lazy/Linux_DST_SCRIPT#4]

**Comment by ChengTu-Lazy** [comment]
64位是内嵌进去的，就跟你用steam下载游戏就是会带64位版本，下载的话是一起下的，不是分开下的，我下个版本会改成只下正式版的，测试版只有在开服前去下载，能解决你的一半苦恼

**Comment by ChengTu-Lazy** [comment]
> 
1.7.5版本已支持默认下载正式版，仅在选在测试服开启的时候下载测试版
